"resources"
{
"materials/darwinian/darwinianskin.vmt" "file"
"materials/darwinian/darwinianskin.vtf" "file"
"materials/darwinian/darwinianskin2.vmt" "file"
"materials/darwinian/darwinianskin2.vtf" "file"
"materials/gob/gobdice.vmt" "file"
"materals/gob/gobdice.vtf" "file"
"models/gob/darwinian.dx80.vtx" "file"
"models/gob/darwinian.dx90.vtx" "file"
"models/gob/darwinian.mdl" "file"
"models/gob/darwinian.phy" "file"
"models/gob/darwinian.sw.vtx" "file"
"models/gob/darwinian.vvd" "file"
"models/gob/gobdice.dx80.vtx" "file"
"models/gob/gobdice.dx90.vtx" "file"
"models/gob/gobdice.mdl" "file"
"models/gob/gobdice.phy" "file"
"models/gob/gobdice.sw.vtx" "file"
"models/gob/gobdice.vvd" "file"
}
