#include "cbase.h"
#include "vgui_util.h"

// ======================================================
// PANEL CLASS (GENERATED BY MACRO)
// ======================================================

PANEL_CREATE(CMyPanel, vgui::Frame, "Panel Title", 500, 400, virtual void Paint();)

// ======================================================
// PANEL FUNCTIONS (ONLY IMPLEMENT WHAT YOU DECLARE)
// ======================================================

void CMyPanel::Paint()
{
	BaseClass::Paint();
}

// ======================================================
// COMMAND (SPAWNS PANEL)
// ======================================================

PANELORHUDCMD(CMyPanel, PanelType_GameUIPanel, open_mypanel, "Open test panel")